### ISSUE TITLE
Retool re-downloads _tools repos on sync even when no need

### ISSUE THREAD

**Issue by gaffo** [twitchtv/retool#27]
even when a tool is correctly up to date in _tools and you sync, retool goes and redownloads that tool. This is bad for several reasons:
- really sucks on slow network connections
- sucks when you have 1/2 of your packages in one private repo behind one corporate firewall and another 1/2 of your packages behind a different firewall
- slower

**Comment by gaffo** [comment]
Basically you should cache the sha of the synced commit off somewhere and only sync if the files (manifest) don't match the sha in tools.json.

**Comment by Fugiman** [comment]
It does. The manifest is stored in the `_tools` directory as `manifest.json` and acts exactly as you state. However it is gitignored by default.

**Comment by gaffo** [comment]
Let me check again. I had some really wierd issue going on where git
thought there was a submodule in play in the _tools directory that I had to
do some wierd commands to get rid of, so it may be that the directories
were there but not the files which made it look like they were. However all
of this was local only, no git push / pull. Just ran sync multiple times
while adding dependencies. Or get.

**Comment by spenczar** [comment]
Adding new dependencies causes a re-sync, which could be better, but as @Fugiman said, retool already caches in this way.
