### ISSUE TITLE
Binary releases of retool itself

### ISSUE THREAD

**Issue by glasser** [twitchtv/retool#35]
As part of bootstrapping use of retool in our process, it would be great if there were binary releases of retool for popular platforms that we can just fetch with a curl against a versioned URL rather than needing to `go get`.

**Comment by spenczar** [comment]
This is a good idea. I think we should be able to do this with gox, github releases, and travis. I'll investigate over the next day or so.

**Comment by spenczar** [comment]
@glasser, I have uploaded binaries for v1.3.5 to github releases. You should be able to get them with curl (you'll need to tell it to follow redirects with `-L`):

```
-> % curl -L https://github.com/twitchtv/retool/releases/download/v1.3.5/retool_darwin_amd64 > retool
-> % chmod +x retool
-> % ./retool version
retool 1.3.5
```

Does this meet your needs? Now's the time to get this right, if there's anything to be improved here.

**Comment by glasser** [comment]
That does hypothetically fit my needs, though I came to the conclusion that vendoring tools with `dep` and installing them with `cd vendor/PKG && go install .` from our build scripts works better for our needs than retool.  (Primarily due to the fact that running two retool sync or do in parallel doesn't work well because of how it deletes the whole _tools tree each time.)  I think if our project had less extensive environment-setup infrastructure scripting already (needed for non-Go tooling) we'd be psyched to use retool though.
