### ISSUE TITLE
work with dep?

### ISSUE THREAD

**Issue by doapp-ryanp** [twitchtv/retool#39]
```
retool add github.com/golang/dep origin/master
retool do dep
retool: fatal err: failed on 'dep': exec: "dep": executable file not found in $PATH
```
Why is this happening?

I could install a `dep` [release](https://github.com/golang/dep/releases) to get it on my $PATH, however isn't that what `retool` is trying to avoid?  

Said another way, shouldn't `retool add github.com/golang/dep origin/master` install the binary local to my project such that `retool do dep` can find and execute it?

**Comment by spenczar** [comment]
`github.com/golang/dep` isn't the right main package. I think you mean to add `github.com/golang/dep/cmd/dep` :)

**Comment by doapp-ryanp** [comment]
Thank you my friend!
