### ISSUE TITLE
Retool is incompatible with Go modules

### ISSUE THREAD

**Issue by jonathaningram** [twitchtv/retool#51]
When I follow the instructions in the README, I can't seem to get retool to add anything successfully. I wonder if retool doesn't work with Go modules and/or Go 1.11.2+?

In the below, notice that I'm running all this outside of `$GOPATH`.

```
MacBook-Pro:myapp Jonathan$ go get github.com/twitchtv/retool
go: finding github.com/twitchtv/retool v1.3.7
go: downloading github.com/twitchtv/retool v1.3.7
go: finding github.com/Masterminds/semver v1.4.2
go: downloading github.com/Masterminds/semver v1.4.2
MacBook-Pro:myapp Jonathan$ retool add github.com/jteeuwen/go-bindata/go-bindata origin/master
retool: downloading github.com/jteeuwen/go-bindata/go-bindata
retool: setting version for github.com/jteeuwen/go-bindata/go-bindata
retool: fatal err: execution error on "git checkout ": chdir /private/tmp/tmpcode/myapp/_tools/src/github.com/jteeuwen/go-bindata/go-bindata: no such file or directory
MacBook-Pro:myapp Jonathan$ retool version
retool 1.3.7
MacBook-Pro:myapp Jonathan$ go version
go version go1.11.2 darwin/amd64
MacBook-Pro:myapp Jonathan$ pwd
/tmp/tmpcode/myapp
MacBook-Pro:myapp Jonathan$ echo $GOPATH
/Users/Jonathan/go
```

As you can see the directory it's looking for doesn't actually exist:

```
MacBook-Pro:myapp Jonathan$ ls -la /private/tmp/tmpcode/myapp/_tools/
total 8
drwxr-xr-x   4 Jonathan  wheel  128  5 Dec 10:18 .
drwxr-xr-x  18 Jonathan  wheel  576  5 Dec 10:18 ..
-rw-r--r--   1 Jonathan  wheel   27  5 Dec 10:20 .gitignore
drwxr-xr-x   3 Jonathan  wheel   96  5 Dec 10:18 pkg
MacBook-Pro:myapp Jonathan$ ls -la /tmp/tmpcode/myapp/_tools/
total 8
drwxr-xr-x   4 Jonathan  wheel  128  5 Dec 10:18 .
drwxr-xr-x  18 Jonathan  wheel  576  5 Dec 10:18 ..
-rw-r--r--   1 Jonathan  wheel   27  5 Dec 10:20 .gitignore
drwxr-xr-x   3 Jonathan  wheel   96  5 Dec 10:18 pkg
```

Does this seem like a bug or is it my issue?

**Comment by 3ventic** [comment]
Works here
```
$ go version
go version go1.11.2 darwin/amd64
$ retool add github.com/jteeuwen/go-bindata/go-bindata origin/master
retool: downloading github.com/jteeuwen/go-bindata/go-bindata
retool: setting version for github.com/jteeuwen/go-bindata/go-bindata
retool: parsing revision "origin/master"
retool: parsed as "6025e8de665b31fa74ab1a66f2cddd8c0abf887e"
retool: installing github.com/jteeuwen/go-bindata/go-bindata
$ retool version
retool 1.3.7
$ pwd
/Users/-me-/go/src/-snip-/-snip-/rt
$ echo $GOPATH
/Users/-me-/go
```

**Comment by jonathaningram** [comment]
@spenczar I've made a repro for this issue: https://github.com/jonathaningram/retool-repro

It's pretty easy to run—you just have to clone my repo and if you've got Docker it should be super quick to see the issue.

I don't think I'm doing anything unusual in the repro so I hope this helps diagnose the issue?

cc @3ventic

**Comment by mrVanboy** [comment]
This is probably caused by go modules. Because retool tries to change directory to `./_tools/src/PACKAGE_PATH`, but in `go modules` mode the correct path should be `./_tools/pkg/mod/PACKAGE_PATH`.

 The simple workaround is to set env variable `GO111MODULE=off` for `revive add` command:

```bash
GO111MODULE=off retool add github.com/mgechev/revive origin/master
```

**Comment by jvsteiner** [comment]
I have this issue too, in my case, using the workaround, required me to set `env GO111MODULE=off` in my Makefile for all commands relating to retool, and also for go generate commands, when the `//go:generate` directive contained a call for retool to `do` something.

**Comment by adamluzsi** [comment]
I have this issue as well,

GO111MODULE is set to on, and files have read only attributes, 
which cause checkout step to fail to me.

**Comment by spenczar** [comment]
Yes, retool is effectively incompatible with Go modules right now in multiple ways. It relies heavily on GOPATH for all of its manipulations - that's how it works, really. It also relies strongly on its belief that import paths and directories are 1:1.

I am not sure this is going to be worth resolving; this might just be the end of retool's life. I think really fixing this would require a full rewrite of retool.

Russ Cox has explicitly described a different "best practice" for managing tools under Go modules: https://github.com/golang/go/issues/25922#issuecomment-413898264

This is more fleshed out on the Go wiki: https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module

I'd encourage you to follow along with those. I think the thing to do here would be write up some documentation on the README.

**Comment by adamluzsi** [comment]
@spenczar thank you very much for your detailed answer, I really appreciate it!

**Comment by jonathaningram** [comment]
@spenczar yes, thank you and it all makes sense. I'm going to close this. Feel free to reopen if you want to.
