### ISSUE TITLE
suggestion: use internal/_tools instead of _tools

### ISSUE THREAD

**Issue by Zemnmez** [twitchtv/retool#52]
because `_tools` potentially contains Go code that isn't stored in `vendor`, tooling, especially those using triple dot syntax (`...`) detects vendored tools as sub-packages.

When I perform audits on code and use `tree`, even blacklisting `vendor` is not enough because retool replicates the source tree and my command explodes

**Comment by GarethLewin** [comment]
https://golang.org/cmd/go/#hdr-Package_lists_and_patterns 

```
Directory and file names that begin with "." or "_" are ignored by the go tool, as are directories named "testdata".
```

**Comment by Zemnmez** [comment]
hmm. I see. Looks like this stems from that the standard libraries don't export an implementation of triple-dot syntax. I still somewhat feel that since this folder contains packages which are not meant to be used externally, the folder should be 'internal'.
